### ISSUE TITLE
QC Summary file not found

### ISSUE THREAD

**Issue by idolawoye** [waglecn/mabs#1]
Hi Nick,

I was trying to test your pipeline for M. abscessus but I encountered this error message when I ran it:

>executing from: /home/olawoyei0303/mabs
Including 11 samples from original 11 samples
QC summary file not found
QC summary file not found
QC summary file not found
QC summary file not found
QC summary file not found
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Singularity containers: ignored
Job counts:
        count   jobs
        1       all
        1
Select jobs to execute...

>[Tue Nov 29 16:20:31 2022]
localrule all:
    jobid: 0

>[Tue Nov 29 16:20:31 2022]
Finished job 0.
1 of 1 steps (100%) done

I am not sure why the QC summary isn't being generated. Looking forward to your response.
Thanks!

**Comment by waglecn** [comment]
Hi! good to hear from you

Can you tell me what command you used to run it, and what version of the
github you pulled?

**Comment by idolawoye** [comment]
Good to hear from you as well!

I pulled the main branch on GitHub and ran it with this command:
`snakemake --configfile config_template.yaml --cores 8 --use-conda`

When I use:
`snakemake --configfile config_template.yaml --cores 8 --use-conda --conda-prefix /home/olawoyei0303/miniconda3/envs/mabs/bin/snakemake`

I have similar error but ends with this instead:
>QC summary file not found
QC summary file not found
QC summary file not found
Traceback (most recent call last):
  File "/home/olawoyei0303/miniconda3/envs/mabs/lib/python3.6/site-packages/snakemake/__init__.py", line 778, in snakemake
    keepmetadata=keep_metadata,
  File "/home/olawoyei0303/miniconda3/envs/mabs/lib/python3.6/site-packages/snakemake/workflow.py", line 690, in execute
    or delete_temp_output,
  File "/home/olawoyei0303/miniconda3/envs/mabs/lib/python3.6/site-packages/snakemake/persistence.py", line 96, in 
 __init__
    os.makedirs(d, exist_ok=True)
  File "/home/olawoyei0303/miniconda3/envs/mabs/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/olawoyei0303/miniconda3/envs/mabs/bin/snakemake'

**Comment by waglecn** [comment]
Okay, no problem!

I was working on adding hybrid nanopore assembly on top of the illumina
assembly, I also did some cleaning of the rules and tidying up. It mostly
runs the same.

Try running stage1 instead of all, all is a dummy rule and I found it
necessary to separate the analysis into different stages. Stage 1 is mostly
QC, and basic assembly, and things that can happen with individual samples.

Nick

**Comment by idolawoye** [comment]
I ran stage1.smk individually but it seems sample_names isn't defined in the script.

>snakemake -s stage1.smk --cores 4
NameError in line 49 of /home/olawoyei0303/mabs/stage1.smk:
name 'sample_names' is not defined
  File "/home/olawoyei0303/mabs/stage1.smk", line 49, in <module>

**Comment by waglecn** [comment]
Okay, we might take a bit to get you going on this, but it's good because
there's lots to learn and I get a chance to make the documentation better

try:

snakemake --configfile config_template.yaml --cores 8 --use-conda stage1

stage1 is the name of the rule, by default it runs the first rule (all) but
since there's nothing defined under that in Snakefile, it doesn't do
anything

did you put the sample names in the sample sheet?

**Comment by idolawoye** [comment]
Ah okay. Yeah the sample sheet is all set up.

I think it's running now as it is currently downloading and installing remote packages

**Comment by waglecn** [comment]
yup, so there is actually a stage0 that downloads reference files and things

Are you on Andrew McArthur's slack? would it be helpful to chat instead of
email?

**Comment by idolawoye** [comment]
Yeah, I'm on Andrew's Superdome slack but I can't find you
*Idowu Olawoye*

**Comment by waglecn** [comment]
I can't find you on the the slack I'm using either, maybe there's another
one I'm not aware of
